### ISSUE TITLE
TypeError: cli() got an unexpected keyword argument 'python_version'

### ISSUE THREAD

**Issue by MrRabbit2MissCat** [QPT-Family/QPT#100]
### QPT版本

1.0b4.dev7

### 操作系统版本

Windows 10

### 核心信息填写

**复现步骤/报错截图**  
PS C:\Users\pc> qpt
→[2023-11-29 11:45:24,503] [DEBUG] | 操作系统类型：Windows
→[2023-11-29 11:45:24,503] [DEBUG] | 操作系统位数：AMD64
[项目文件夹]请输入待打包的文件夹路径: C:\Users\pc\Desktop\code\sample_program
[主程序文件]请输入待打包的主要Py脚本文件路径: C:\Users\pc\Desktop\code\sample_program\main.py
[输出目录]请输入打包后文件保存的路径: C:\Users\pc\Desktop\code\out
[Python依赖]请输入requirements.txt文件路径，若无该文件可直接按下[回车键]自动生成该文件 [auto]:
Traceback (most recent call last):
  File "d:\software\python3.8\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\software\python3.8\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\python3.8\Scripts\qpt.exe\__main__.py", line 7, in <module>
  File "d:\software\python3.8\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "d:\software\python3.8\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "d:\software\python3.8\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\software\python3.8\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'python_version'
  
## 步骤描述  
输入qpt, 按要求写入路径报错，应该是command.py里的问题
![image](https://github.com/QPT-Family/QPT/assets/38371806/cefb31c1-809d-4dcd-bcbf-c0f28706d554)

  
## 【如报错则必须提供】Requirements文件内容 
  
```  
↓建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↓  
  
Example:  
  
paddlepaddle==2.2.2  
opencv-python>=4.1  
...  
  
↑建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↑  
```  
  
## 【如报错则必须提供】完整打包日志   
```  
↓建议在此处粘贴完整日志↓  
  
↑建议在此处粘贴完整日志↑  
```  
  
## 完整运行日志（如打包时已报错，此处可选）  
  
```  
↓建议在此处粘贴完整日志↓  
  
↑建议在此处粘贴完整日志↑  
```

**Comment by GT-ZhangAcer** [comment]
感谢，是这里的问题，这两天回家测试一下就进行更新

**Comment by MrRabbit2MissCat** [comment]
不客气😊

**Comment by GT-ZhangAcer** [comment]
1.0b7已修正，感谢参与！
