### ISSUE TITLE
KeyError: '~illow'

### ISSUE THREAD

**Issue by fanweiya** [QPT-Family/QPT#22]
打包时中断，出现这个错误
```
正在搜索依赖    26/25  |████████████████████| 104.00% 对应文件:./detection_FL12\utils\loggers\wandb\__init__.pyTraceback (most recent call last):
  File "F:\Anaconda\envs\tf2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Anaconda\envs\tf2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Anaconda\envs\tf2\Scripts\qpt.exe\__main__.py", line 7, in <module>
  File "F:\Anaconda\envs\tf2\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "F:\Anaconda\envs\tf2\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "F:\Anaconda\envs\tf2\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\Anaconda\envs\tf2\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "F:\Anaconda\envs\tf2\lib\site-packages\qpt\command.py", line 77, in cli
    icon=icon)
  File "F:\Anaconda\envs\tf2\lib\site-packages\qpt\executor.py", line 154, in __init__
    deploy_mode=deploy_mode)
  File "F:\Anaconda\envs\tf2\lib\site-packages\qpt\modules\auto_requirements.py", line 34, in __init__
    requirements = PIP.analyze_dependence(path, return_path=False)
  File "F:\Anaconda\envs\tf2\lib\site-packages\qpt\kernel\tools\qinterpreter.py", line 168, in analyze_dependence
    if dep[require_name]:
KeyError: '~illow'
```

**Comment by GT-ZhangAcer** [comment]
已知问题，该版本替代方案如下：  
1. 在非Conda环境下的Python环境进行打包
2. 在打包时指定requirements文件，这样就可以避开自动搜索依赖，从而避免该问题

**Comment by fanweiya** [comment]
> 1. 在非Conda环境下的Python环境进行打包
> 2. 在打包时指定requirements文件，这样就可以避开自动搜索依赖，从而避免该问题

请问一下如果我不在Conda下打包的话，能把Cuda打包进去吗

**Comment by GT-ZhangAcer** [comment]
这个版本还没加Conda的支持哈，目前打包CUDA的话需要在本地有安装CUDA。最近太忙，快的话这周就加上这个并把刚刚的那个给修了

**Comment by GT-ZhangAcer** [comment]
新版本1.0b1.dev6修复完毕
