### ISSUE TITLE
【可能的Bug】ImportError: DLL load failed: 找不到指定的模块

### ISSUE THREAD

**Issue by fanweiya** [QPT-Family/QPT#34]
隐藏窗口打包，拷贝Release复制到其他目录测试是否隐藏，打开后报下面的错误并闪退
```
2021-11-17 17:41:31,536 DEBUG: 终端命令执行成功！
2021-11-17 17:41:31,536 DEBUG: 正在连接PTerminal
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\CellCounter\gsdfsdfRelease\Python\lib\site-packages\qpt\run.py", line 13, in <module>
    module.run()
  File "D:\CellCounter\gsdfsdfRelease\Python\lib\site-packages\qpt\executor.py", line 463, in run
    msg = warning_msg_box("Warning", f"非常不建议在该环境下进行调试，原因如下： \n"
  File "D:\CellCounter\gsdfsdfRelease\Python\lib\site-packages\qpt\kernel\qos.py", line 223, in warning_msg_box
    win32api = QPT_MEMORY.get_win32api
  File "D:\CellCounter\gsdfsdfRelease\Python\lib\site-packages\qpt\memory.py", line 19, in render
    out = func(self)
  File "D:\CellCounter\gsdfsdfRelease\Python\lib\site-packages\qpt\memory.py", line 67, in get_win32api
    import win32api
ImportError: DLL load failed: 找不到指定的模块
```

**Comment by yangy996** [comment]
大佬，怎么解决的，我还是报这个错误
