### ISSUE TITLE
文件下载失败，报错如下：<urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by zhangyingying520** [QPT-Family/QPT#41]
请键入指令[回车键 - 一次不行可以试试按两次]:_
2022-03-07 13:54:55,364 INFO: ----------QPT执行使用了以下OP----------
2022-03-07 13:54:55,364 INFO: AutoPythonEnv执行优先级5.0	{'Pack': ['PackPythonEnvOpt'], 'Unpack': ['UnPackPythonEnvOpt']}
2022-03-07 13:54:55,364 INFO: QPTDependencyPackage执行优先级3.0	{'Pack': ['OnlineInstallWhlOpt', 'OnlineInstallWhlOpt', 'DownloadWhlOpt'], 'Unpack': ['LocalInstallWhlOpt']}
2022-03-07 13:54:55,364 INFO: ----------程序执行使用了以下OP----------
2022-03-07 13:54:55,364 INFO: AutoRequirementsPackage优先级3.0	{'Pack': ['DownloadWhlOpt'], 'Unpack': ['LocalInstallWhlOpt']}
2022-03-07 13:54:55,364 INFO: BatchInstallation优先级2.0	{'Pack': [], 'Unpack': ['BatchInstallationOpt']}
2022-03-07 13:54:55,365 INFO: ------------------------------------
2022-03-07 13:54:55,365 INFO: 正在加载AutoPythonEnv-PackPythonEnvOptOP
2022-03-07 13:54:55,365 INFO: 正在加载Python解释器原文件至C:\Users\15301\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev2\Python\4726320339
2022-03-07 13:54:55,562 ERROR: 无法下载文件，请检查网络是否可以连接以下链接
https://bj.bcebos.com/v1/ai-studio-online/ea6af2820f594d209d6dc421b9392327d270368a6fb2428ebf8bd90cd74d7e26?responseContentDisposition=attachment%3B%20filename%3DPython39.zip
若该文件由QPT提供，请升级QPT版本，若版本升级后仍未解决可在以下地址提交issue反馈该情况
https://github.com/GT-ZhangAcer/QPT/issues
Traceback (most recent call last):
  File "C:\anaconda3\envs\paddle1\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\anaconda3\envs\paddle1\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\anaconda3\envs\paddle1\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\anaconda3\envs\paddle1\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\anaconda3\envs\paddle1\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\anaconda3\envs\paddle1\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\anaconda3\envs\paddle1\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\anaconda3\envs\paddle1\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\anaconda3\envs\paddle1\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\anaconda3\envs\paddle1\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\anaconda3\envs\paddle1\lib\site-packages\qpt\kernel\qos.py", line 85, in download
    wget.download(url, file_path)
  File "C:\anaconda3\envs\paddle1\lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "C:\anaconda3\envs\paddle1\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\anaconda3\envs\paddle1\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\anaconda3\envs\paddle1\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\anaconda3\envs\paddle1\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\anaconda3\envs\paddle1\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\anaconda3\envs\paddle1\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\anaconda3\envs\paddle1\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Test_Build\qpt2exe.py", line 13, in <module>
    module.make()
  File "C:\anaconda3\envs\paddle1\lib\site-packages\qpt\executor.py", line 219, in make
    self._solve_module(lazy=True)
  File "C:\anaconda3\envs\paddle1\lib\site-packages\qpt\executor.py", line 202, in _solve_module
    sub.pack()
  File "C:\anaconda3\envs\paddle1\lib\site-packages\qpt\modules\base.py", line 172, in pack
    opt.run(op_path)
  File "C:\anaconda3\envs\paddle1\lib\site-packages\qpt\modules\base.py", line 73, in run
    self.act()
  File "C:\anaconda3\envs\paddle1\lib\site-packages\qpt\modules\python_env.py", line 55, in act
    d_result = download(self.url, "Python.zip", dir_name)
  File "C:\anaconda3\envs\paddle1\lib\site-packages\qpt\kernel\qos.py", line 92, in download
    raise Exception("文件下载失败，报错如下：" + str(e))
Exception: 文件下载失败，报错如下：<urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

**Comment by GT-ZhangAcer** [comment]
优先检查网络环境并关闭代理
