### ISSUE TITLE
[Bug report]CPU支持AVX但是脚本却提示不支持AVX指令集

### ISSUE THREAD

**Issue by nine-city** [QPT-Family/QPT#53]
**简要描述Bug**

**基本信息**
QPT版本：1.0b3.dev7
操作系统版本：win 10 x64
CPU型号或AVX支持情况：
intel i5 12400  SSE4.1/4.2，AVX2

**复现步骤/报错截图**
步骤描述：  
完整打包日志： 
2022-04-13 18:07:26,472 DEBUG: 终端命令执行成功！
初始化进度 18:076/8  |━━━━━━━━━━━━━━━     | 75.00% BatchInstallation部署中...2022-04-13 18:07:26,473 DEBUG: 正在加载BatchInstallation-BatchInstallationOptOP
2022-04-13 18:07:26,508 INFO: 需要补充的安装包数量为：0
初始化进度 18:077/8  |━━━━━━━━━━━━━━━━━   | 87.50% PaddlePaddleCheckAVX部署中...2022-04-13 18:07:26,510 DEBUG: 正在加载PaddlePaddleCheckAVX-CheckAVXOptOP
2022-04-13 18:07:27,232 WARNING: cannot import name 'ImageOps' from 'PIL' (D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\PIL\__init__.py)
2022-04-13 18:07:27,234 WARNING: 为保证可以成功在NoAVX平台执行PaddlePaddle，即将忽略小版本号进行安装PaddlePaddle-NoAVX
2022-04-13 18:07:27,234 WARNING: 当前CPU不支持AVX指令集，正在尝试在线下载noavx版本的PaddlePaddle
2022-04-13 18:07:27,234 DEBUG: SHELL: cd D: ;D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip uninstall paddlepaddle -y --isolated --disable-pip-version-check --cache-dir C:\Users\QY\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-04-13 18:07:27,236 DEBUG: (base) PS D:\desktop\project\python\pyseg\EISeg\out\Debug> cd D: ;D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip uninstall paddlepaddle -y --isolated --disable-pip-version-check --cache-dir C:\Users\QY\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-04-13 18:07:27,534 DEBUG: Usage:
2022-04-13 18:07:27,534 DEBUG:   D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip uninstall [options] <package> ...
2022-04-13 18:07:27,535 DEBUG:   D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip uninstall [options] -r <requirements file> ...
2022-04-13 18:07:27,535 DEBUG: no such option: --prefer-binary
2022-04-13 18:07:27,560 DEBUG: 终端命令执行成功！
2022-04-13 18:07:27,560 DEBUG: SHELL: cd D: ;D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir C:\Users\QY\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-04-13 18:07:27,562 DEBUG: (base) PS D:\desktop\project\python\pyseg\EISeg\out\Debug> cd D: ;D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir C:\Users\QY\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-04-13 18:07:27,875 DEBUG: Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html
2022-04-13 18:07:28,134 DEBUG: ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
2022-04-13 18:07:28,134 DEBUG: ERROR: No matching distribution found for paddlepaddle
2022-04-13 18:07:28,163 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
(base) PS D:\desktop\project\python\pyseg\EISeg\out\Debug> cd D: ;D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir C:\Users\QY\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle

初始化进度 18:078/8  |━━━━━━━━━━━━━━━━━━━━| 100.00% 初始化完毕2022-04-13 18:07:28,164 INFO:
2022-04-13 18:07:28,180 INFO: ----------WARNING SUMMARY
2022-04-13 18:07:28,180 INFO: 0|cannot import name 'ImageOps' from 'PIL' (D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\PIL\__init__.py)

2022-04-13 18:07:28,181 INFO: 1|为保证可以成功在NoAVX平台执行PaddlePaddle，即将忽略小版本号进行安装PaddlePaddle-NoAVX

2022-04-13 18:07:28,181 INFO: 2|当前CPU不支持AVX指令集，正在尝试在线下载noavx版本的PaddlePaddle

2022-04-13 18:07:28,181 INFO: ----------ERROR SUMMARY
2022-04-13 18:07:28,181 INFO: 3|在执行终端命令时检测到了失败，完整信息如下：
(base) PS D:\desktop\project\python\pyseg\EISeg\out\Debug> cd D: ;D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir C:\Users\QY\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle

2022-04-13 18:07:28,182 INFO: ----------生成状态WARNING:3 ERROR:1
2022-04-13 18:15:46,935 DEBUG: SHELL: cd "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources";./../Python/python.exe "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources\run.py"
(base) PS D:\desktop\project\python\pyseg\EISeg\out\Debug> cd "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources";./../Python/python.exe "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources\run.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources\run.py", line 26, in <module>
    from app import APP_EISeg  # 导入带槽的界面
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources\app.py", line 26, in <module>
    from eiseg.util.opath import check_cn
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\eiseg\util\__init__.py", line 4, in <module>
    from .polygon import get_polygon, Instructions
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\eiseg\util\polygon.py", line 20, in <module>
    from .regularization import boundary_regularization
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\eiseg\util\regularization\__init__.py", line 21, in <module>
    from .rs_regularization import boundary_regularization
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\eiseg\util\regularization\rs_regularization.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
ImportError: cannot import name 'Image' from 'PIL' (D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\PIL\__init__.py)
2022-04-13 18:15:47,340 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
(base) PS D:\desktop\project\python\pyseg\EISeg\out\Debug> cd "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources";./../Python/python.exe "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources\run.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources\run.py", line 26, in <module>
    from app import APP_EISeg  # 导入带槽的界面
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\resources\app.py", line 26, in <module>
    from eiseg.util.opath import check_cn
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\eiseg\util\__init__.py", line 4, in <module>
    from .polygon import get_polygon, Instructions
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\eiseg\util\polygon.py", line 20, in <module>
    from .regularization import boundary_regularization
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\eiseg\util\regularization\__init__.py", line 21, in <module>
    from .rs_regularization import boundary_regularization
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\eiseg\util\regularization\rs_regularization.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
ImportError: cannot import name 'Image' from 'PIL' (D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\Lib\site-packages\PIL\__init__.py)
完整运行日志：（如打包时已报错，此处可选）  

# 以上信息请务必提供，如未提供以上信息，该issue将默认忽略+close，不做任何支持，需要您的配合。

**我的建议**

**其他**

**Comment by GT-ZhangAcer** [comment]
当前版本的Hidden Terminal模式中TK与Pillow在部分环境存在冲突，可考虑以下方案解决该问题：
1. 打包时调整`hidden_terminal`为`False`。（推荐）
2. 回退QPT版本至更早版本，由于QPT目前仍未发布稳定版，故该方案可能会引发意料外的问题。
3. 新增SubModule，手动解决TK与Pillow冲突。

**Comment by nine-city** [comment]
QPT打包过程中根据方案1和方案2都没有报错，但是打包paddle的eiseg数据标注工具还是启动不起来。

具体日志
D:\desktop\project\python\pyseg\EISeg\out\Release>"./Python/python.exe" -c "import sys;sys.path.append('./Python');sys.path.append('./Python/Lib');sys.path.append('./Python/Lib/site-packages');sys.path.append('./Python/Scripts');import qpt.run as run"
D:\desktop\project\python\pyseg\EISeg\out\Release\Python\Lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2022-04-14 09:19:47,622 INFO: QPT Runtime版本号为1.0b3.dev7，若无法使用该程序，可向程序发布者或GitHub: QPT-Family/QPT提 交issue寻求帮助
2022-04-14 09:19:51,499 INFO: 初次使用将会适应本地环境，可能需要几分钟时间，请耐心等待...
初始化进度 09:198/8  |━━━━━━━━━━━━━━━━━━━━| 100.00% 初始化完毕2022-04-14 09:19:51,505 INFO: 9:19:51,505 INFO: O:
2022-04-14 09:19:51,505 INFO: ----------WARNING SUMMARY
2022-04-14 09:19:51,505 INFO: ----------ERROR SUMMARY
2022-04-14 09:19:51,505 INFO: ----------生成状态WARNING:0 ERROR:0
(base) PS D:\desktop\project\python\pyseg\EISeg\out\Release> cd "D:\desktop\project\python\pyseg\EISeg\out\Release\resources";./../Python/python.exe "D:\desktop\project\python\pyseg\EISeg\out\Release\resources\run.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
D:\desktop\project\python\pyseg\EISeg\out\Release\Python\Lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
D:\desktop\project\python\pyseg\EISeg\out\Release\Python\Lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
D:\desktop\project\python\pyseg\EISeg\out\Release\Python\Lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
D:\desktop\project\python\pyseg\EISeg\out\Release\Python\Lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
D:\desktop\project\python\pyseg\EISeg\out\Release\Python\Lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
D:\desktop\project\python\pyseg\EISeg\out\Release\Python\Lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING

D:\desktop\project\python\pyseg\EISeg\out\Release>pause
Press any key to continue . . .

**Comment by GT-ZhangAcer** [comment]
可以尝试以下方式做异常排除：

**Comment by GT-ZhangAcer** [comment]
可以尝试以下流程做异常排除：
1. 贴出打包相关代码
2. 在待打包主程序的头部，插入形如print("test")的代码，确定是否是代码兼容性存在问题

**Comment by nine-city** [comment]
就是拉取的paddle官方的的EISEG源代码，什么都没改。
以下是我的打包代码。

`#coding=utf-8
from qpt.smart_opt import set_default_pip_source
from qpt.executor import CreateExecutableModule as CEM
from qpt.modules.package import CopyWhl2Packages

set_default_pip_source("https://mirror.baidu.com/pypi/simple")
module = CEM(work_dir="./eiseg",                              # [项目文件夹]待打包的目录，并且该目录下需要有↓下方提到的py文件
             launcher_py_path="./eiseg/exe.py",                  # [主程序文件]用户启动EXE文件后，QPT要执行的py文件
             save_path="./out",       # [输出目录]打包后相关文件的输出目录
             requirements_file="./requirements.txt",                    # [Python依赖]此处可填入依赖文件路径，也可设置为auto自动搜索依赖
             hidden_terminal=False,
             sub_modules=[
                CopyWhl2Packages('D:/desktop/project/python/pyseg/EISeg/GDAL-3.4.2-cp37-cp37m-win_amd64.whl')  # 修改这一行
             ]
             )   
module.make()`
