### ISSUE TITLE
[Report] 由于使用到pymupdf库，打包失败

### ISSUE THREAD

**Issue by jackielee2012** [QPT-Family/QPT#64]
### QPT版本

1.0b3.dev7

### 操作系统版本

Windows 10

### 核心信息填写

**复现步骤/报错截图**  
  
## 步骤描述  
（可描述您参考了哪些文档中的步骤，或自己在做哪些操作时遇到了问题，社区维护者可以通过该描述来尽可能复现您的情况）
  
## 【如报错则必须提供】Requirements文件内容 
  
```  
↓建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↓  
  
Example:  
  
paddlepaddle==2.2.2  
opencv-python>=4.1  
...  
  
↑建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↑  
```  
  
## 【如报错则必须提供】完整打包日志   
```  
↓建议在此处粘贴完整日志↓  
  
↑建议在此处粘贴完整日志↑  
```  
  
## 完整运行日志（如打包时已报错，此处可选）  
  
```  
2022-05-18 18:15:50,559 DEBUG: 终端命令执行成功！
2022-05-18 18:15:50,561 DEBUG: SHELL: cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\PyWavelets-1.3.0-cp38-cp38-win_amd64.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-05-18 18:15:50,566 DEBUG: PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\PyWavelets-1.3.0-cp38-cp38-win_amd64.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-05-18 18:15:51,836 DEBUG: Processing d:\pyspace\lee\out\debug\opt\packages\pywavelets-1.3.0-cp38-cp38-win_amd64.whl
2022-05-18 18:15:52,226 DEBUG: Installing collected packages: PyWavelets
2022-05-18 18:15:53,099 DEBUG: Successfully installed PyWavelets-1.3.0
2022-05-18 18:15:53,165 DEBUG: 终端命令执行成功！
2022-05-18 18:15:53,167 DEBUG: SHELL: cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\scikit_image-0.19.2-cp38-cp38-win_amd64.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-05-18 18:15:53,171 DEBUG: PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\scikit_image-0.19.2-cp38-cp38-win_amd64.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-05-18 18:15:54,564 DEBUG: Processing d:\pyspace\lee\out\debug\opt\packages\scikit_image-0.19.2-cp38-cp38-win_amd64.whl
2022-05-18 18:15:54,973 DEBUG: Installing collected packages: scikit-image
2022-05-18 18:16:01,738 DEBUG: Successfully installed scikit-image-0.19.2
2022-05-18 18:16:01,805 DEBUG: 终端命令执行成功！
2022-05-18 18:16:01,807 DEBUG: SHELL: cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\scipy-1.8.0-cp38-cp38-win_amd64.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-05-18 18:16:01,813 DEBUG: PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\scipy-1.8.0-cp38-cp38-win_amd64.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-05-18 18:16:03,089 DEBUG: Processing d:\pyspace\lee\out\debug\opt\packages\scipy-1.8.0-cp38-cp38-win_amd64.whl
2022-05-18 18:16:03,513 DEBUG: Installing collected packages: scipy
2022-05-18 18:16:19,229 DEBUG: Successfully installed scipy-1.8.0
2022-05-18 18:16:19,301 DEBUG: 终端命令执行成功！
2022-05-18 18:16:19,303 DEBUG: SHELL: cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\Shapely-1.8.2-cp38-cp38-win_amd64.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-05-18 18:16:19,308 DEBUG: PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\Shapely-1.8.2-cp38-cp38-win_amd64.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-05-18 18:16:20,585 DEBUG: Processing d:\pyspace\lee\out\debug\opt\packages\shapely-1.8.2-cp38-cp38-win_amd64.whl
2022-05-18 18:16:20,995 DEBUG: Installing collected packages: Shapely
2022-05-18 18:16:21,705 DEBUG: Successfully installed Shapely-1.8.2
2022-05-18 18:16:21,776 DEBUG: 终端命令执行成功！
2022-05-18 18:16:21,778 DEBUG: SHELL: cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\tifffile-2022.5.4-py3-none-any.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-05-18 18:16:21,784 DEBUG: PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\tifffile-2022.5.4-py3-none-any.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-05-18 18:16:23,068 DEBUG: Processing d:\pyspace\lee\out\debug\opt\packages\tifffile-2022.5.4-py3-none-any.whl
2022-05-18 18:16:23,479 DEBUG: Installing collected packages: tifffile
2022-05-18 18:16:24,402 DEBUG: Successfully installed tifffile-2022.5.4
2022-05-18 18:16:24,470 DEBUG: 终端命令执行成功！
2022-05-18 18:16:24,472 DEBUG: SHELL: cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\tqdm-4.64.0-py2.py3-none-any.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-05-18 18:16:24,476 DEBUG: PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install D:\pyspace\lee\out\Debug\opt/packages\tqdm-4.64.0-py2.py3-none-any.whl --no-index --no-deps -i https://mirrors.bfsu.edu.cn/pypi/web/simple --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-05-18 18:16:25,799 DEBUG: Processing d:\pyspace\lee\out\debug\opt\packages\tqdm-4.64.0-py2.py3-none-any.whl
2022-05-18 18:16:26,210 DEBUG: Installing collected packages: tqdm
2022-05-18 18:16:26,847 DEBUG: Successfully installed tqdm-4.64.0
2022-05-18 18:16:26,912 DEBUG: 终端命令执行成功！
初始化进度 18:1610/11  |━━━━━━━━━━━━━━━━━━  | 90.91% PaddlePaddleCheckAVX部署中...2022-05-18 18:16:26,918 DEBUG: 正在加 载PaddlePaddleCheckAVX-CheckAVXOptOP
2022-05-18 18:16:30,763 WARNING: cannot import name 'ImageOps' from 'PIL' (D:\pyspace\lee\out\Debug\Python\Lib\site-packages\PIL\__init__.py)
2022-05-18 18:16:30,767 WARNING: 为保证可以成功在NoAVX平台执行PaddlePaddle，即将忽略小版本号进行安装PaddlePaddle-NoAVX
2022-05-18 18:16:30,767 WARNING: 当前CPU不支持AVX指令集，正在尝试在线下载noavx版本的PaddlePaddle
2022-05-18 18:16:30,769 DEBUG: SHELL: cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip uninstall paddlepaddle -y --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-05-18 18:16:30,770 DEBUG: PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip uninstall paddlepaddle -y --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-05-18 18:16:32,065 DEBUG: Usage:
2022-05-18 18:16:32,066 DEBUG:   D:\pyspace\lee\out\Debug\Python\python.exe -m pip uninstall [options] <package> ...
2022-05-18 18:16:32,067 DEBUG:   D:\pyspace\lee\out\Debug\Python\python.exe -m pip uninstall [options] -r <requirements file> ...
2022-05-18 18:16:32,068 DEBUG: no such option: --prefer-binary
2022-05-18 18:16:32,124 DEBUG: 终端命令执行成功！
2022-05-18 18:16:32,126 DEBUG: SHELL: cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary
2022-05-18 18:16:32,133 DEBUG: PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
2022-05-18 18:16:33,400 DEBUG: Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html
2022-05-18 18:16:33,657 DEBUG: Collecting paddlepaddle
2022-05-18 18:16:33,995 DEBUG:   Downloading https://paddle-wheel.bj.bcebos.com/2.3.0/windows/windows-cpu-mkl-noavx/paddlepaddle-2.3.0-cp38-cp38-win_amd64.whl (64.2 MB)
2022-05-18 18:16:41,141 DEBUG: Installing collected packages: paddlepaddle
2022-05-18 18:16:41,141 DEBUG:   Attempting uninstall: paddlepaddle
2022-05-18 18:16:41,146 DEBUG:     Found existing installation: paddlepaddle 2.3.0
2022-05-18 18:16:43,680 DEBUG:     Uninstalling paddlepaddle-2.3.0:
2022-05-18 18:16:43,797 DEBUG:       Successfully uninstalled paddlepaddle-2.3.0
2022-05-18 18:17:02,704 DEBUG: ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\pyspace\\lee\\out\\Debug\\Python\\Lib\\site-packages\\~addle\\fluid\\core_avx.pyd'
2022-05-18 18:17:02,704 DEBUG: Consider using the `--user` option or check the permissions.
2022-05-18 18:17:02,785 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html
Collecting paddlepaddle
  Downloading https://paddle-wheel.bj.bcebos.com/2.3.0/windows/windows-cpu-mkl-noavx/paddlepaddle-2.3.0-cp38-cp38-win_amd64.whl (64.2 MB)
Installing collected packages: paddlepaddle
  Attempting uninstall: paddlepaddle
    Found existing installation: paddlepaddle 2.3.0
    Uninstalling paddlepaddle-2.3.0:
      Successfully uninstalled paddlepaddle-2.3.0
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\pyspace\\lee\\out\\Debug\\Python\\Lib\\site-packages\\~addle\\fluid\\core_avx.pyd'
Consider using the `--user` option or check the permissions.

初始化进度 18:1711/11  |━━━━━━━━━━━━━━━━━━━━| 100.00% 初始化完毕2022-05-18 18:17:02,787 INFO:
2022-05-18 18:17:02,805 INFO: ----------WARNING SUMMARY
2022-05-18 18:17:02,805 INFO: 0|cannot import name 'ImageOps' from 'PIL' (D:\pyspace\lee\out\Debug\Python\Lib\site-packages\PIL\__init__.py)


2022-05-18 18:17:02,806 INFO: 1|为保证可以成功在NoAVX平台执行PaddlePaddle，即将忽略小版本号进行安装PaddlePaddle-NoAVX


2022-05-18 18:17:02,806 INFO: 2|当前CPU不支持AVX指令集，正在尝试在线下载noavx版本的PaddlePaddle


2022-05-18 18:17:02,807 INFO: ----------ERROR SUMMARY
2022-05-18 18:17:02,807 INFO: 3|在执行终端命令时检测到了失败，完整信息如下：
PS D:\pyspace\lee\out\Debug> cd D: ;D:\pyspace\lee\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir D:\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html
Collecting paddlepaddle
  Downloading https://paddle-wheel.bj.bcebos.com/2.3.0/windows/windows-cpu-mkl-noavx/paddlepaddle-2.3.0-cp38-cp38-win_amd64.whl (64.2 MB)
Installing collected packages: paddlepaddle
  Attempting uninstall: paddlepaddle
    Found existing installation: paddlepaddle 2.3.0
    Uninstalling paddlepaddle-2.3.0:
      Successfully uninstalled paddlepaddle-2.3.0
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\pyspace\\lee\\out\\Debug\\Python\\Lib\\site-packages\\~addle\\fluid\\core_avx.pyd'
Consider using the `--user` option or check the permissions.



2022-05-18 18:17:02,808 INFO: ----------生成状态WARNING:3 ERROR:1
2022-05-18 18:18:44,914 DEBUG: SHELL: cd "D:\pyspace\lee\out\Debug\resources";./../Python/python.exe "D:\pyspace\lee\out\Debug\resources\myapp.py"
PS D:\pyspace\lee\out\Debug> cd "D:\pyspace\lee\out\Debug\resources";./../Python/python.exe "D:\pyspace\lee\out\Debug\resources\myapp.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "D:\pyspace\lee\out\Debug\resources\myapp.py", line 17, in <module>
    import pdf
  File "D:\pyspace\lee\out\Debug\resources\pdf.py", line 2, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'
2022-05-18 18:18:45,239 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS D:\pyspace\lee\out\Debug> cd "D:\pyspace\lee\out\Debug\resources";./../Python/python.exe "D:\pyspace\lee\out\Debug\resources\myapp.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "D:\pyspace\lee\out\Debug\resources\myapp.py", line 17, in <module>
    import pdf
  File "D:\pyspace\lee\out\Debug\resources\pdf.py", line 2, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'
```  
  
## 其他信息
1. 官方说法
[pymupdf官方文档说明](https://pymupdf.readthedocs.io/en/latest/intro.html#note-on-the-name-fitz)
这个库的顶级 Python 导入名称是“fitz”。 这有历史原因：

MuPDF 的原始渲染库称为 Libart。

“在 Artifex Software 收购 MuPDF 项目后，开发重点转移到了编写一个名为“Fitz”的新现代图形库上。 Fitz 最初的目的是作为一个研发项目来取代老化的 Ghostscript 图形库，但现在却成为了支持 MuPDF 的渲染引擎。” （引自维基百科）。

所以 PyMuPDF 不能在同一个 Python 环境中与名为“fitz”的包共存。

2. 已经手动将pymupdf的包加入requirements_with_opt.txt文件

**Comment by GT-ZhangAcer** [comment]
最新版本已修复PaddlePaddle部分的问题，如仍需手动添加pymupdf，可在Issue中继续回复 https://github.com/QPT-Family/QPT/releases/tag/V1.0b3
