### ISSUE TITLE
[Report]CLI模式运行报错

### ISSUE THREAD

**Issue by zyklone4096** [QPT-Family/QPT#66]
### QPT版本

1.0b3

### 操作系统版本

Windows 11

### CPU型号

Intel i5-9400F

### 核心信息填写

**复现步骤/报错截图**  
  
## 步骤描述  
使用控制台打包，除目录以外的选项与 README.md 相同
  
## 【如报错则必须提供】Requirements文件内容 
  
```  
↓建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↓  
  
Example:  
  
# Here is the list of packages automatically derived by QPT
# you can ignore the dependent packages in the main package and only care about the main package
# For example, you need to install paddlepaddle and pillow, because paddlepaddle relies on pillow, so you only need to install paddlepaddle.
# ---------------------------------------------------------------------
# QPT Home:        https://github.com/GT-ZhangAcer/QPT
# ---------------------------------------------------------------------
# 
# -------------Mainly depends on package analysis results--------------

mixaclib==2.2.0
easyocr==1.5.0
translate==3.6.1
torchvision==0.12.0
pyqt5==5.15.6

# ----------------------Ignored dependent packages---------------------
#you_get==0.4.1555
#wheel==0.37.1
#tqdm==4.64.0
#torchaudio==0.11.0
#qpt==1.0b3.dev10
#pywin32==304
#pyside2==5.15.2.1
#pyinstaller==5.0.1
#pycord==0.1.1
#pyautogui==0.9.53
#opencv_python==4.5.5.64
#mcstatus==9.0.4
#matplotlib==3.5.2
#jieba==0.42.1
#bilili==1.4.11
#bilibili==0.0.1
#bilibili_api==9.1.0
#aiosignal==1.2.0

# ----------------------Ignored sub dependent packages---------------------

# -----Dependencies of easyocr
#scikit_image
#numpy
#python_bidi
#pyyaml
#torch
#opencv_python_headless<=4.5.4.60
#pillow
#torchvision>=0.5
#scipy

# -----Dependencies of translate
#requests
#lxml
#click
#libretranslatepy==2.1.1

# -----Dependencies of torchvision
#pillow!=8.3.*,>=5.3.0
#numpy
#requests
#torch==1.11.0
#typing_extensions

# -----Dependencies of pyqt5
#pyqt5_qt5>=5.15.2
#pyqt5_sip<13,>=12.8

...  
  
↑建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↑  
```  
  
## 【如报错则必须提供】完整打包日志   
```  
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python310\Scripts\qpt.exe\__main__.py", line 7, in <module>
  File "D:\Program Files\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Program Files\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Program Files\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\qpt\command.py", line 78, in cli
    module.make()
  File "D:\Program Files\Python310\lib\site-packages\qpt\executor.py", line 229, in make
    self._solve_module()
  File "D:\Program Files\Python310\lib\site-packages\qpt\executor.py", line 211, in _solve_module
    sub.pack()
  File "D:\Program Files\Python310\lib\site-packages\qpt\modules\base.py", line 260, in pack
    opt.run(op_path)
  File "D:\Program Files\Python310\lib\site-packages\qpt\modules\base.py", line 184, in run
    self.act()
  File "D:\Program Files\Python310\lib\site-packages\qpt\modules\package.py", line 442, in act
    for whl in self.existing_offline_installation_packages:
  File "D:\Program Files\Python310\lib\site-packages\qpt\modules\base.py", line 122, in existing_offline_installation_packages
    whl_list = [whl for whl in os.listdir(self.download_packages_path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '.\\out\\Release\\opt/packages'
```  
  
## 完整运行日志（如打包时已报错，此处可选）  
  
```  

```

**Comment by zyklone4096** [comment]
运行命令
`qpt.exe -f .\ -p .\main.py -s .\out -h False`

**Comment by zyklone4096** [comment]
问题已不在出现

**Comment by GT-ZhangAcer** [comment]
你这个头像...有点孙哥哈哈哈  
你那边是咋样解决的呢，或者说是怎样出现的呢？如果是QPT的Bug，那还是要修一下的

**Comment by zyklone4096** [comment]
> 你这个头像...有点孙哥哈哈哈 你那边是咋样解决的呢，或者说是怎样出现的呢？如果是QPT的Bug，那还是要修一下的

就正常运行，python3.10版本
