### ISSUE TITLE
Release\使用兼容模式运行.cmd 提示ModuleNotFoundError: No module named 'win32api' opt里面有此包

### ISSUE THREAD

**Issue by dreamscience** [QPT-Family/QPT#76]
### QPT版本

1.0b4

### 操作系统版本

Windows 10

### CPU型号

E5-2696V3

### 核心信息填写

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\PADDTEST\dabao\Release\Python\Lib\site-packages\qpt\executor.py", line 488, in run
    msg = warning_msg_box("Warning", f"非常不建议在该环境下进行调试，原因如下： \n"
  File "D:\PADDTEST\dabao\Release\Python\Lib\site-packages\qpt\kernel\qos.py", line 245, in warning_msg_box
    win32api = QPT_MEMORY.get_win32api
  File "D:\PADDTEST\dabao\Release\Python\Lib\site-packages\qpt\memory.py", line 26, in render
    out = func(self)
  File "D:\PADDTEST\dabao\Release\Python\Lib\site-packages\qpt\memory.py", line 83, in get_win32api
    import win32api
ModuleNotFoundError: No module named 'win32api'

D:\PADDTEST\dabao\Release>pause
Press any key to continue . . .

**Comment by Wintrw** [comment]
遇到了同一个问题，分享一下解决方案：在release文件夹下使用命令提示符，运行
`"./Python/python.exe" "-m" "pip" "install" "pywin32"`
手动安装pywin32库，可以解决问题。
