### ISSUE TITLE
打包exe后，出现FileNotFoundError: [Errno 2] No such file or directory: './12.ui'

### ISSUE THREAD

**Issue by guoliangxie123** [QPT-Family/QPT#88]
### QPT版本

1.0b4.dev6

### 操作系统版本

Windows 10

### 核心信息填写

Traceback (most recent call last):
  File "E:\code\python\python-text-recognition-master2\python-text-recognition-master\out\Release1\resources\src\baidu-api.py", line 855, in <module>
    Ui_MainWindow, QtBaseClass = uic.loadUiType(qtCreatorFile)
  File "E:\code\python\python-text-recognition-master2\python-text-recognition-master\out\Release1\Python\Lib\site-packages\PyQt5\uic\__init__.py", line 203, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports,
  File "E:\code\python\python-text-recognition-master2\python-text-recognition-master\out\Release1\Python\Lib\site-packages\PyQt5\uic\Compiler\compiler.py", line 111, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "E:\code\python\python-text-recognition-master2\python-text-recognition-master\out\Release1\Python\Lib\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
  File "E:\code\python\python-text-recognition-master2\python-text-recognition-master\out\Release1\Python\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "E:\code\python\python-text-recognition-master2\python-text-recognition-master\out\Release1\Python\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './12.ui'

--------------------------------------------------------------------------------------------------------------------------------------
代码中引用了相对路径，但是打包后点击exe程序发现找不到这个相对路径；但是在pycharm中可以正常运行的
望回复~

**Comment by GT-ZhangAcer** [comment]
Pycharm可能会把当前目录作为工作目录，比较建议的是以下两种方式
1. 在Pycharm里设置项目的根目录为工作目录，或尝试自行调整项目资源所用到的相对路径。
2. 也可以用sys.path.append将对应资源路径添加
